name: Secure DevOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-and-build:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout the source code from your repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Run an automated Trivy scan directly inside the pipeline
    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1' # Hardening: Stop the build if vulnerabilities are found
        severity: 'CRITICAL,HIGH'

    # 3. Setup Terraform CLI inside the GitHub runner
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    # 4. Verify Infrastructure code layout compliance
    - name: Terraform Validate
      run: |
        cd terraform
        terraform init -backend=false
        terraform validate

    # 5. Build the production Docker container if security tests pass
    - name: Build Hardened Docker Image
      run: |
        docker build -t secure-python-app:latest ./app# Ensure you are at the project root
